exportDefaults:
  defaultDirectory: "saves"
  defaultFilename: "data"
  defaultAllowOverwrite: false
  defaultSortColumn: 0
  defaultSeparator: ";"

pointsConfig:
  xMin: 0
  xMax: 100
  yMin: 0
  yMax: 100
  tMin: 0
  tMax: 1000
  decimalPrecision: 2

profilesFilePath: "colorProfiles.yaml"

# gotta rework how the languages are split

languagesSupported:
 - "fr"
 - "en"

defaultLang: "en"

viewTexts:
  fr:
    exportButton: "exporter"
    exportLabel: "nom du fichier exporté:"
    addPointButton: "Ajouter point aléatoire"
    langFrenchButton: "Francais"
    langEnglishButton: "Anglais"
    separatorSwitchButton: "Changer separateur CSV"
    colorSwitch: "changer les couleurs"
    colorProfile: "Profile couleurs: "
  en:
    exportButton: "export"
    exportLabel: "export filename :"
    addPointButton: "Add random point"
    langFrenchButton: "French"
    langEnglishButton: "English"
    separatorSwitchButton: "Change CSV separator"
    colorSwitch: "change colors"
    colorProfile: "Current color profile: "



messages:
  fr:
    exportSuccess: "Sauvegarde réussie, fichier sauvegardé vers\n"
    exportErrorOverwrite: "Sauvegarde échoué,\n le fichier existe deja"
    exportErrorUnknown: "Sauvegarde échoué"
    addPoint: "Point ajouté :\n"
    separatorSwitch: "Séparateur CSV changé vers :\n"
    languageChanged: "Language changé en :"
  en:
    exportSuccess: "Export successful, file saved to\n"
    exportErrorOverwrite: "Export failed,\n the file already exists"
    exportErrorUnknown: "Export failed"
    addPoint: "Point added :\n"
    separatorSwitch: "CSV separator set to :\n"
    languageChanged: "Language set to :"



exportHeaders:
    fr:
      time: "temps"
      posX: "positionX"
      posY: "positionY"
    en:
      time: "time"
      posX: "positionX"
      posY: "positionY"